services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto-service/config/:/mosquitto/config/
      - ./mosquitto-service/log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  web-service:
    build: ./flask-service
    ports:
      - "5000:5000"
    volumes:
      - .:/code
volumes:
  data: ~
