---
version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    user: mosquitto
    volumes:
      - type: bind
        source: ./mqtt-service/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mqtt-service/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/dataa/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
  config-publisher:
    build: ./python-services/publishers
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - mosquitto
  temperature-subscriber:
    build: ./python-services/subscribers
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - mosquitto
  client:
    build: ./python-services/client
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - temperature-subscriber

volumes:
  data:
    name: "mqtt-broker-data"

networks:
  default:
    name: mqtt-network