/*
 * generated by Xtext 2.30.0
 */
package sdu.abba;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EnvironmentalMonitoringStandaloneSetup extends EnvironmentalMonitoringStandaloneSetupGenerated {

	public static void doSetup() {
		new EnvironmentalMonitoringStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
