/*
 * generated by Xtext 2.30.0
 */
package sdu.abba.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EnvironmentalMonitoringUiModule extends AbstractEnvironmentalMonitoringUiModule {

	public EnvironmentalMonitoringUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
