/*
 * generated by Xtext 2.30.0
 */
package sdu.abba.ide;


/**
 * Use this class to register ide components.
 */
public class EnvironmentalMonitoringIdeModule extends AbstractEnvironmentalMonitoringIdeModule {
}
